AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket for Cloudfrontbeat
Parameters:
  BucketName:
    Description: Bucket Name (passed in from main template)
    Type: String
  QueueARN:
    Description: SQS queue ARN (passed in from main template)
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref BucketName
      NotificationConfiguration:
        QueueConfigurations:
        - Queue: !Ref QueueARN
          Event: s3:ObjectCreated:*
      Tags:
      - Key: Name
        Value: !Ref BucketName

Outputs:
  BucketName:
    Description: S3 bucket name
    Value: !Ref S3Bucket
  DomainName:
    Description: Domain name for S3 bucket
    Value: !GetAtt S3Bucket.DomainName
